export const REGIONS_CI = [
  "Abidjan (District autonome)",
  "Yamoussoukro (District autonome)",
  "Agnéby-Tiassa",
  "Bafing",
  "Bagoué",
  "Bélier",
  "Béré",
  "Bounkani",
  "Cavally",
  "Folon",
  "Gbêkê",
  "Gôh",
  "Gontougo",
  "Grands Ponts",
  "Guémon",
  "Hambol",
  "Iffou",
  "Indénié-Djuablin",
  "Kabadougou",
  "La Mé",
  "Lôh-Djiboua",
  "Marahoué",
  "Moronou",
  "Nawa",
  "N'Zi",
  "Poro",
  "San-Pédro",
  "Sud-Bandama",
  "Sud-Comoé",
  "Tchologo",
  "Tonkpi",
  "Vallée du Bandama",
  "Worodougou",
] as const;
