// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // `migrate deploy` a besoin d'une connexion directe (non-pooled) pour
    // pouvoir poser un advisory lock — la connexion pooled Neon échoue avec
    // l'erreur P1002 (timeout) sur cette opération.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
